export const CONTRACT_ADDRESSES = {
  DEALIX_DEX: import.meta.env.VITE_DEALIX_DEX_ADDRESS || '',
  DEALIX_LOCKER: import.meta.env.VITE_DEALIX_LOCKER_ADDRESS || '',
  DEALIX_FACTORY: import.meta.env.VITE_DEALIX_FACTORY_ADDRESS || '',
  DEALIX_ROUTER: import.meta.env.VITE_DEALIX_ROUTER_ADDRESS || '',
  BADGE_MANAGER: import.meta.env.VITE_BADGE_MANAGER_ADDRESS || '',
  LIQUIDITY_BALANCER: import.meta.env.VITE_LIQUIDITY_BALANCER_ADDRESS || '',
  REWARD_DISTRIBUTOR: import.meta.env.VITE_REWARD_DISTRIBUTOR_ADDRESS || '',
} as const;